### ISSUE TITLE
Add way to use any point as base size

### ISSUE THREAD

**Issue by meodai** [meodai/dialog-size#4]
would be nice to have a way to use a named size as an absolute point.

something like

``` scss
.foo {
     font-size: size(small, +1);
}
```

would return the next bigger size after small.

and

``` scss
.foo {
     font-size: size(small, -1);
}
```

would return a size that is one smaller then small.

What do you guys think? @ingvijonasson @Nirazul
