### ISSUE TITLE
Add way to use the last used size

### ISSUE THREAD

**Issue by orioltf** [meodai/dialog-size#7]
In the same way ther are the `bigger`and `smaller` keywords, another useful keyword would be for instance `current`.

Use case:

```scss
@mixin burrito($baseSize: 'spaceRegular') {
	padding-top: size(setting($baseSize));
	padding-bottom: size(setting($baseSize));

	@include mq($from: small) {
		padding-top: size(bigger);
		padding-bottom: size(current);
	}

	@include mq($from: medium) {
		padding-top: size(larger);
		padding-bottom: size(current);
	}
}
```

What do you think? would it be too tricky?
